(set-language-environment "UTF-8")

(setq package-archives '(("gnu" . "https://mirrors.ustc.edu.cn/elpa/gnu/")
			 ("melpa" . "https://mirrors.ustc.edu.cn/elpa/melpa/")
			 ("nongnu" . "https://mirrors.ustc.edu.cn/elpa/nongnu/")))

(add-to-list 'load-path "~/.emacs.d/site-lisp")

(let ((backup-dir "~/tmp/emacs/backups")
      (auto-saves-dir "~/tmp/emacs/auto-saves/"))
  (dolist (dir (list backup-dir auto-saves-dir))
    (when (not (file-directory-p dir))
      (make-directory dir t)))
  (setq backup-directory-alist `(("." . ,backup-dir))
	auto-save-file-name-transforms `((".*" ,auto-saves-dir t))
	auto-save-list-file-prefix (concat auto-saves-dir ".saves-")
	tramp-backup-directory-alist `((".*" . ,backup-dir))
	tramp-auto-save-directory auto-saves-dir))

(setq backup-by-copying t    ; Don't delink hardlinks
      delete-old-versions t  ; Clean up the backups
      version-control t      ; Use version numbers on backups,
      kept-new-versions 5    ; keep some new versions
      kept-old-versions 2)   ; and some old ones, too

(setq inhibit-startup-screen t)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(menu-bar-mode -1)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq indent-line-function 'insert-tab)

(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
;(load-theme 'gruvbox t)
;(load-theme 'catppuccin t)

(global-display-line-numbers-mode)

(add-to-list 'default-frame-alist '(font . "DejaVu Sans Mono-12"))
(defun my/set-font-faces ()
  (message "Setting faces!")
  (set-fontset-font "fontset-default" 'han "sarasa-gothic")
  (set-face-attribute 'fixed-pitch nil :font "DejaVu Sans Mono" :height 120)
  (set-face-attribute 'variable-pitch nil :font "DejaVu Sans Mono" :height 120 :weight 'regular))

(if (daemonp)
    (add-hook 'server-after-make-frame-hook
	      (lambda () (my/set-font-faces)))
    (my/set-font-faces))

(setq verilog-indent-level 4)
(setq verilog-indent-level-module 0)
(setq verilog-indent-level-declaration 0)
(setq verilog-case-indent 4)
(setq verilog-cexp-indent 4)
(setq verilog-indent-lists nil)
(setq verilog-indent-level-behavioral 4)
(setq verilog-indent-level-directive 4)
(setq verilog-auto-indent-on-newline nil)
(setq verilog-tab-always-indent t)
(setq verilog-indent-begin-after-if nil)
(setq verilog-auto-newline nil)
(setq verilog-auto-endcomments t)
(setq verilog-auto-reset-widths t)
(setq verilog-assignment-delay "#1 ")
(setq verilog-auto-lineup nil)

(defun  my/insert-verilog-file-header ()
  "Insert headers to Verilog files."
  (interactive)
  (setq cur-file (read-from-minibuffer "file name ? " 
		 (file-name-nondirectory (buffer-file-name))))
  (setq cur-date (org-read-date))
  (setq cur-author "Tao Yuxin")
  (setq cur-email "ytaoai@connect.ust.hk")
  (setq cur-description (read-from-minibuffer "description ? "))
  (insert (format "//****************************************************************\\\n"))
  (insert (format "// Copyright (C) %s %s, All right reserved.\n" (format-time-string "%Y") cur-author))
  (insert (format "// File        : %s \n" cur-file))
  (insert (format "// Author      : %s \n" cur-author))
  (insert (format "// E-mail      : %s \n" cur-email))
  (insert (format "// date        : %s \n" cur-date))
  (insert (format "// Description : %s \n" cur-description))
  (insert (format "//****************************************************************/\n"))
  (insert (format "\n"))
  (insert (format "// synopsys translate_off\n"))
  (insert (format "`timescale 1ns/1ps\n"))
  (insert (format "// synopsys translate_on\n"))
  (insert (format "\n"))
  (insert (format "module %s\n" (file-name-base cur-file)))
  (insert (format "#(\n"))
  (insert (format "    parameter TDLY = 1\n"))
  (insert (format ")\n"))
  (insert (format "(\n"))
  (insert (format "    input wire clk,\n"))
  (insert (format "    input wire rst_n,\n"))
  (insert (format "    input wire i_dat,\n"))
  (insert (format "    output wire o_dat\n"))
  (insert (format ");\n"))
  (insert (format "\n"))
  (insert (format "\n"))
  (insert (format "\n"))
  (insert (format "\n"))
  (insert (format "endmodule\n")))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (setq meow-beacon-indicator-delay 20)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))
(require 'meow)
(meow-setup)
(meow-global-mode 1)

(define-key key-translation-map (kbd "C-;") [escape])
(fido-vertical-mode 1)
(with-eval-after-load 'completion-preview
  (define-key completion-preview-active-mode-map (kbd "C-n") #'completion-preview-next-candidate)
  (define-key completion-preview-active-mode-map (kbd "C-p") #'completion-preview-prev-candidate))
(global-completion-preview-mode 1)

(setq custom-file (concat user-emacs-directory "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file))
